insert into public.city (if_played, name) values (false, 'Abu Dhabi');
insert into public.city (if_played, name) values (false, 'Agra');
insert into public.city (if_played, name) values (false, 'Albuquerque');
insert into public.city (if_played, name) values (false, 'Aleppo');
insert into public.city (if_played, name) values (false, 'Babruysk');
insert into public.city (if_played, name) values (false, 'Baku');
insert into public.city (if_played, name) values (false, 'Baltimore');
insert into public.city (if_played, name) values (false, 'Bangkok');
insert into public.city (if_played, name) values (false, 'Cairo');
insert into public.city (if_played, name) values (false, 'Cambridge');
insert into public.city (if_played, name) values (false, 'Cape Town');
insert into public.city (if_played, name) values (false, 'Cartagena');
insert into public.city (if_played, name) values (false, 'Dallas');
insert into public.city (if_played, name) values (false, 'Donetsk');
insert into public.city (if_played, name) values (false, 'Delhi');
insert into public.city (if_played, name) values (false, 'Detroit');
insert into public.city (if_played, name) values (false, 'Edinburgh');
insert into public.city (if_played, name) values (false, 'English Bazar');
insert into public.city (if_played, name) values (false, 'Engels');
insert into public.city (if_played, name) values (false, 'Elista');
insert into public.city (if_played, name) values (false, 'Fargo');
insert into public.city (if_played, name) values (false, 'Ferrara');
insert into public.city (if_played, name) values (false, 'Florence');
insert into public.city (if_played, name) values (false, 'Fuji');
insert into public.city (if_played, name) values (false, 'Ganzhou');
insert into public.city (if_played, name) values (false, 'Giza');
insert into public.city (if_played, name) values (false, 'Geneva');
insert into public.city (if_played, name) values (false, 'Glasgow');
insert into public.city (if_played, name) values (false, 'Hamburg');
insert into public.city (if_played, name) values (false, 'Hanoi');
insert into public.city (if_played, name) values (false, 'Havana');
insert into public.city (if_played, name) values (false, 'Heraklion');
insert into public.city (if_played, name) values (false, 'Idlib');
insert into public.city (if_played, name) values (false, 'Ichikawa');
insert into public.city (if_played, name) values (false, 'Innsbruck');
insert into public.city (if_played, name) values (false, 'Irkutsk');
insert into public.city (if_played, name) values (false, 'Jaipur');
insert into public.city (if_played, name) values (false, 'Jingzhou');
insert into public.city (if_played, name) values (false, 'Johannesburg');
insert into public.city (if_played, name) values (false, 'Jersey City');
insert into public.city (if_played, name) values (false, 'Kabul');
insert into public.city (if_played, name) values (false, 'Kaliningrad');
insert into public.city (if_played, name) values (false, 'Kamianets-Podilskyi');
insert into public.city (if_played, name) values (false, 'Kansas City');
insert into public.city (if_played, name) values (false, 'Leipzig');
insert into public.city (if_played, name) values (false, 'Leicester');
insert into public.city (if_played, name) values (false, 'Leeds');
insert into public.city (if_played, name) values (false, 'Lille');
insert into public.city (if_played, name) values (false, 'Macau');
insert into public.city (if_played, name) values (false, 'Madrid');
insert into public.city (if_played, name) values (false, 'Magnitogorsk');
insert into public.city (if_played, name) values (false, 'Makiivka');
insert into public.city (if_played, name) values (false, 'Nagano');
insert into public.city (if_played, name) values (false, 'Nakhodka');
insert into public.city (if_played, name) values (false, 'Naples');
insert into public.city (if_played, name) values (false, 'New York');
insert into public.city (if_played, name) values (false, 'Oakland');
insert into public.city (if_played, name) values (false, 'Okinawa');
insert into public.city (if_played, name) values (false, 'Omsk');
insert into public.city (if_played, name) values (false, 'Orsha');
insert into public.city (if_played, name) values (false, 'Padua');
insert into public.city (if_played, name) values (false, 'Panama City');
insert into public.city (if_played, name) values (false, 'Paris');
insert into public.city (if_played, name) values (false, 'Parma');
insert into public.city (if_played, name) values (false, 'Qarshi');
insert into public.city (if_played, name) values (false, 'Qianjiang');
insert into public.city (if_played, name) values (false, 'Quetta');
insert into public.city (if_played, name) values (false, 'Qufu');
insert into public.city (if_played, name) values (false, 'Reykjavík');
insert into public.city (if_played, name) values (false, 'Richmond');
insert into public.city (if_played, name) values (false, 'Riga');
insert into public.city (if_played, name) values (false, 'Rio de Janeiro');
insert into public.city (if_played, name) values (false, 'Saint Petersburg');
insert into public.city (if_played, name) values (false, 'Salt Lake City');
insert into public.city (if_played, name) values (false, 'San Sebastián');
insert into public.city (if_played, name) values (false, 'Santa Fe');
insert into public.city (if_played, name) values (false, 'Taipei');
insert into public.city (if_played, name) values (false, 'Tambov');
insert into public.city (if_played, name) values (false, 'Tel Aviv');
insert into public.city (if_played, name) values (false, 'Ternopil');
insert into public.city (if_played, name) values (false, 'Uzhhorod');
insert into public.city (if_played, name) values (false, 'Ulyanovsk');
insert into public.city (if_played, name) values (false, 'Ulan-Ude');
insert into public.city (if_played, name) values (false, 'Udine');
insert into public.city (if_played, name) values (false, 'Vinnytsia');
insert into public.city (if_played, name) values (false, 'Vitebsk');
insert into public.city (if_played, name) values (false, 'Vilnius');
insert into public.city (if_played, name) values (false, 'Verona');
insert into public.city (if_played, name) values (false, 'Warsaw');
insert into public.city (if_played, name) values (false, 'Wellington');
insert into public.city (if_played, name) values (false, 'Wichita');
insert into public.city (if_played, name) values (false, 'Wolfsburg');
insert into public.city (if_played, name) values (false, 'Xochimilco');
insert into public.city (if_played, name) values (false, 'Xai-Xai');
insert into public.city (if_played, name) values (false, 'Xiangyang');
insert into public.city (if_played, name) values (false, 'Xiamen');
insert into public.city (if_played, name) values (false, 'Yakutsk');
insert into public.city (if_played, name) values (false, 'Yenakiieve');
insert into public.city (if_played, name) values (false, 'Yamato');
insert into public.city (if_played, name) values (false, 'York');
insert into public.city (if_played, name) values (false, 'Zanzibar City');
insert into public.city (if_played, name) values (false, 'Zaporizhia');
insert into public.city (if_played, name) values (false, 'Zhytomyr');
insert into public.city (if_played, name) values (false, 'Zagreb');
